In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
X[1]

array([608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
      dtype=object)

In [4]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [5]:
ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(X)

In [6]:
X[1]

array([0.0, 0.0, 1.0, 608, 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
      dtype=object)

In [7]:
X[:, 4]

array(['Female', 'Female', 'Female', ..., 'Female', 'Male', 'Female'],
      dtype=object)

In [8]:
labelencoder_X = LabelEncoder()
X[:, 4] = labelencoder_X.fit_transform(X[:, 4])

In [9]:
X = X[:, 1:]

In [10]:
X.shape

(10000, 11)

In [11]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [12]:
X_train[1]

array([0.0, 0.0, 541, 1, 39, 7, 0.0, 2, 1, 0, 19823.02], dtype=object)

In [13]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [15]:
# Initialising the ANN
classifier = Sequential()

In [16]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [17]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [18]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [19]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [20]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
7000/7000 [==============================] - 1s 152us/step - loss: 0.4878 - accuracy: 0.7969
Epoch 2/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.4179 - accuracy: 0.7977
Epoch 3/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.4077 - accuracy: 0.7977
Epoch 4/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3991 - accuracy: 0.8224
Epoch 5/100
7000/7000 [==============================] - 1s 109us/step - loss: 0.3913 - accuracy: 0.8313
Epoch 6/100
7000/7000 [==============================] - 1s 108us/step - loss: 0.3845 - accuracy: 0.8326
Epoch 7/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3800 - accuracy: 0.8361
Epoch 8/100
7000/7000 [==============================] - 1s 110us/step - loss: 0.3759 - accuracy: 0.8421
Epoch 9/100
7000/7000 [==============================] - 1s 119us/step - loss: 0.3721 - accuracy: 0.8476
Epoch 10/100
7000/7000 [==============================]

7000/7000 [==============================] - 1s 121us/step - loss: 0.3464 - accuracy: 0.8586
Epoch 79/100
7000/7000 [==============================] - 1s 121us/step - loss: 0.3460 - accuracy: 0.8594
Epoch 80/100
7000/7000 [==============================] - 1s 119us/step - loss: 0.3459 - accuracy: 0.8604
Epoch 81/100
7000/7000 [==============================] - 1s 117us/step - loss: 0.3452 - accuracy: 0.8606
Epoch 82/100
7000/7000 [==============================] - 1s 117us/step - loss: 0.3455 - accuracy: 0.8574
Epoch 83/100
7000/7000 [==============================] - 1s 125us/step - loss: 0.3464 - accuracy: 0.8594
Epoch 84/100
7000/7000 [==============================] - 1s 119us/step - loss: 0.3459 - accuracy: 0.8594
Epoch 85/100
7000/7000 [==============================] - 1s 117us/step - loss: 0.3456 - accuracy: 0.8584
Epoch 86/100
7000/7000 [==============================] - 1s 117us/step - loss: 0.3456 - accuracy: 0.8603
Epoch 87/100
7000/7000 [==============================] - 1

In [21]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [22]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm = confusion_matrix(y_test, y_pred)

In [23]:
cm

array([[2225,  154],
       [ 276,  345]], dtype=int64)

In [24]:
cls_report = classification_report(y_test, y_pred)
print(cls_report)

              precision    recall  f1-score   support

           0       0.89      0.94      0.91      2379
           1       0.69      0.56      0.62       621

    accuracy                           0.86      3000
   macro avg       0.79      0.75      0.76      3000
weighted avg       0.85      0.86      0.85      3000



In [25]:
acr = accuracy_score(y_test, y_pred)
print(acr)

0.8566666666666667


In [26]:
(2225 + 345)/ 3000

0.8566666666666667